//
// Ce fichier a été généré par l'implémentation de référence JavaTM Architecture for XML Binding (JAXB), v2.2.8-b130911.1802 
// Voir <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Toute modification apportée à ce fichier sera perdue lors de la recompilation du schéma source. 
// Généré le : 2016.10.04 à 11:04:45 AM GMT 
//


package com.ngis.civairs.model.statics;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Classe Java pour VL313_5_0_1_1.
 * 
 * <p>Le fragment de schéma suivant indique le contenu attendu figurant dans cette classe.
 * <p>
 * <pre>
 * &lt;simpleType name="VL313_5_0_1_1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Light"/>
 *     &lt;enumeration value="Medium"/>
 *     &lt;enumeration value="Heavy"/>
 *     &lt;enumeration value="Super"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VL313_5_0_1_1")
@XmlEnum
public enum VL3135011 {


    /**
     * The wake turbulence generated by aircraft with a maximum take-off mass of 7000 kg or less. ICAO Doc 9426
     * 
     */
    @XmlEnumValue("Light")
    LIGHT("Light"),

    /**
     * The wake turbulence generated by aircraft with a maximum take-off mass greater than 7000 kg but no more than 136 000 kg. ICAO Doc 9426
     * 
     */
    @XmlEnumValue("Medium")
    MEDIUM("Medium"),

    /**
     * The wake turbulence generated by aircraft with a maximum take-off mass greater than 136 000 kg. ICAO Doc 9426
     * 
     */
    @XmlEnumValue("Heavy")
    HEAVY("Heavy"),

    /**
     * A380 and similar aircraft
     * 
     */
    @XmlEnumValue("Super")
    SUPER("Super"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    VL3135011(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VL3135011 fromValue(String v) {
        for (VL3135011 c: VL3135011 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
